# -*- coding: utf-8 -*-
"""
提示词模板模块

说明：
- 本模块定义特定任务的提示词模板和公共规则
- 按功能拆分为多个子模块：common, outline, chapter, conclusion, ultra
"""

from .common import (
    PDF_MULTIMODAL_GUIDE,
    ROLE_AND_STYLE_GUIDE,
    QUALITY_CONTROL_RULES,
    DEDUPLICATION_INSTRUCTION_WITH_PREVIOUS,
    DEDUPLICATION_INSTRUCTION_FIRST,
    PREVIOUS_CHAPTER_CONTEXT_TEMPLATE,
)

from .outline import OUTLINE_PROMPT_TEMPLATE

from .chapter import (
    CHAPTER_DEPTH_CONSTRAINT_TEMPLATE,
    CHAPTER_PROMPT_TEMPLATE,
)

from .conclusion import CONCLUSION_PROMPT_TEMPLATE

from .ultra import (
    DEEP_OUTLINE_INSTRUCTIONS,
    ULTRA_OUTLINE_INSTRUCTIONS,
    ULTRA_CHAPTER_INSTRUCTIONS,
)

__all__ = [
    # Common
    'PDF_MULTIMODAL_GUIDE',
    'ROLE_AND_STYLE_GUIDE',
    'QUALITY_CONTROL_RULES',
    'DEDUPLICATION_INSTRUCTION_WITH_PREVIOUS',
    'DEDUPLICATION_INSTRUCTION_FIRST',
    'PREVIOUS_CHAPTER_CONTEXT_TEMPLATE',
    # Outline
    'OUTLINE_PROMPT_TEMPLATE',
    # Chapter
    'CHAPTER_DEPTH_CONSTRAINT_TEMPLATE',
    'CHAPTER_PROMPT_TEMPLATE',
    # Conclusion
    'CONCLUSION_PROMPT_TEMPLATE',
    # Ultra / Deep
    'DEEP_OUTLINE_INSTRUCTIONS',
    'ULTRA_OUTLINE_INSTRUCTIONS',
    'ULTRA_CHAPTER_INSTRUCTIONS',
]
