# 自适应内容长度生成配置文件
# 此文件控制基于视频特征的动态长度计算参数

# 基础长度比例 - 相对于原始字幕长度的比例
base_ratios:
  short: 0.7      # 短视频（<20分钟）：70%
  medium: 0.8     # 中等视频（20-60分钟）：80%
  long: 0.9       # 长视频（60-120分钟）：90%
  extra_long: 1.0 # 超长视频（>120分钟）：100%

# 信息密度调整系数 - 基于每分钟字数的调整
density_multipliers:
  low: 1.2    # 低密度（<100字/分钟）：增加20%
  medium: 1.0 # 中密度（100-200字/分钟）：保持不变
  high: 0.8   # 高密度（>200字/分钟）：减少20%

# 章节数量范围 - 不同视频类型的章节数量范围
chapter_ranges:
  short: [8, 12]      # 短视频：8-12章节
  medium: [12, 16]    # 中等视频：12-16章节
  long: [16, 20]      # 长视频：16-20章节
  extra_long: [20, 25] # 超长视频：20-25章节

# 长度边界限制
min_article_length: 8000   # 最小文章长度（字）
max_article_length: 60000  # 最大文章长度（字）

# 长度容差范围（±百分比）
length_tolerance: 0.2  # 20%的容差范围

# 配置说明：
# 1. base_ratios: 控制不同时长视频的基础长度比例
#    - 短视频通常信息密度较高，使用较低比例
#    - 长视频可能包含更多细节，使用较高比例
#
# 2. density_multipliers: 根据语速调整长度
#    - 低密度视频（慢语速）需要更多文字来充实内容
#    - 高密度视频（快语速）信息量大，可适当压缩
#
# 3. chapter_ranges: 章节数量影响文章结构
#    - 更多章节意味着更细致的分析
#    - 章节数量会在指定范围内随机选择
#
# 4. 边界限制确保生成的文章长度在合理范围内
#
# 5. length_tolerance 允许一定的长度偏差，提供灵活性

# 调优建议：
# - 如果生成的文章普遍过短，可以增加 base_ratios 的值
# - 如果生成的文章普遍过长，可以减少 base_ratios 的值
# - 根据实际使用情况调整 density_multipliers
# - 可以根据用户偏好调整 chapter_ranges