"""Cookie Store - 管理 Cookie 的存储和加载"""
import json
import logging
from pathlib import Path
from typing import Optional
from datetime import datetime

from .models import Cookie, CookieMetadata

logger = logging.getLogger(__name__)


class CookieStore:
    """Cookie 存储管理器"""
    
    def __init__(self, store_path: Optional[Path] = None, netscape_path: Optional[Path] = None):
        """
        初始化 Cookie Store
        
        Args:
            store_path: JSON 格式的 cookie 存储路径（默认 ~/.cookies.json）
            netscape_path: Netscape 格式的 cookie 导出路径（默认 ~/.cookies，用于 yt-dlp）
        """
        # 使用用户主目录作为默认路径
        if store_path is None:
            store_path = Path.home() / ".cookies.json"
        if netscape_path is None:
            netscape_path = Path.home() / ".cookies"
        
        self.store_path = Path(store_path)
        self.netscape_path = Path(netscape_path)
        
        # 确保父目录存在
        self.store_path.parent.mkdir(parents=True, exist_ok=True)
        self.netscape_path.parent.mkdir(parents=True, exist_ok=True)
    
    def load_cookies(self) -> list[dict]:
        """
        从 JSON 文件加载 cookies
        
        Returns:
            Cookie 列表（字典格式）
        """
        if not self.store_path.exists():
            logger.warning(f"Cookie 文件不存在: {self.store_path}")
            return []
        
        try:
            with open(self.store_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            cookies = data.get('cookies', [])
            
            # 标准化 cookies，确保 expires 字段是正确的类型
            standardized_cookies = []
            for cookie in cookies:
                # 确保 expires 是 float 或 None
                if 'expires' in cookie and cookie['expires'] is not None:
                    try:
                        cookie['expires'] = float(cookie['expires'])
                    except (ValueError, TypeError):
                        logger.warning(f"Cookie {cookie.get('name')} 的 expires 字段无效，设置为 None")
                        cookie['expires'] = None
                standardized_cookies.append(cookie)
            
            logger.info(f"成功加载 {len(standardized_cookies)} 个 cookies")
            return standardized_cookies
        
        except json.JSONDecodeError as e:
            logger.error(f"解析 Cookie 文件失败: {e}")
            return []
        except Exception as e:
            logger.error(f"加载 Cookie 文件失败: {e}")
            return []
    
    def save_cookies(self, cookies: list[dict], metadata: Optional[dict] = None) -> None:
        """
        保存 cookies 到 JSON 文件，并同时导出为 Netscape 格式
        
        Args:
            cookies: Cookie 列表（字典格式）
            metadata: Cookie 元数据
        """
        if metadata is None:
            metadata = CookieMetadata().model_dump()
        
        # 保存 JSON 格式
        data = {
            "cookies": cookies,
            "metadata": metadata
        }
        
        try:
            with open(self.store_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            
            logger.info(f"成功保存 {len(cookies)} 个 cookies 到 {self.store_path}")
            
            # 同时导出为 Netscape 格式
            self.export_to_netscape(self.netscape_path)
            
        except Exception as e:
            logger.error(f"保存 Cookie 文件失败: {e}")
            raise
    
    def get_metadata(self) -> dict:
        """
        获取 cookie 元数据
        
        Returns:
            元数据字典
        """
        if not self.store_path.exists():
            return CookieMetadata().model_dump()
        
        try:
            with open(self.store_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            return data.get('metadata', CookieMetadata().model_dump())
        
        except Exception as e:
            logger.error(f"读取元数据失败: {e}")
            return CookieMetadata().model_dump()
    
    def export_to_netscape(self, output_path: Path) -> None:
        """
        将 cookies 导出为 Netscape 格式（供 yt-dlp 使用）
        
        Args:
            output_path: 输出文件路径
        """
        cookies = self.load_cookies()
        if not cookies:
            logger.warning("没有 cookies 可导出")
            return
        
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                # 写入 Netscape 格式的头部
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by Cookie Manager\n")
                f.write("# Edit at your own risk.\n\n")
                
                # 转换每个 cookie
                for cookie_dict in cookies:
                    try:
                        cookie = Cookie(**cookie_dict)
                        f.write(cookie.to_netscape_line() + "\n")
                    except Exception as e:
                        logger.warning(f"跳过无效的 cookie: {e}")
                        continue
            
            logger.info(f"成功导出 Netscape 格式 cookies 到 {output_path}")
            
            # 设置文件权限为 600（仅所有者可读写）
            try:
                output_path.chmod(0o600)
            except Exception as e:
                logger.warning(f"设置文件权限失败: {e}")
        
        except Exception as e:
            logger.error(f"导出 Netscape 格式失败: {e}")
            raise
    
    def is_valid(self) -> bool:
        """
        检查存储的 cookies 是否有效
        
        Returns:
            True 如果 cookies 有效，否则 False
        """
        cookies = self.load_cookies()
        if not cookies:
            return False
        
        # 检查是否有 YouTube 域名的 cookies
        youtube_cookies = [c for c in cookies if 'youtube.com' in c.get('domain', '')]
        if not youtube_cookies:
            logger.warning("没有找到 YouTube 域名的 cookies")
            return False
        
        # 检查是否有过期的 cookies
        try:
            for cookie_dict in youtube_cookies:
                cookie = Cookie(**cookie_dict)
                if cookie.is_expired():
                    logger.warning(f"Cookie 已过期: {cookie.name}")
                    # 注意：即使有过期的 cookie，我们仍然认为整体有效
                    # 因为其他 cookies 可能仍然有效
        except Exception as e:
            logger.warning(f"检查 cookie 过期状态失败: {e}")
        
        # 检查元数据中的验证状态
        metadata = self.get_metadata()
        validation_status = metadata.get('validation_status', 'unknown')
        
        if validation_status == 'invalid':
            logger.warning("Cookies 标记为无效")
            return False
        
        return True
    
    def update_metadata(self, **kwargs) -> None:
        """
        更新元数据
        
        Args:
            **kwargs: 要更新的元数据字段
        """
        metadata = self.get_metadata()
        metadata.update(kwargs)
        
        cookies = self.load_cookies()
        self.save_cookies(cookies, metadata)
